name: "nawc DevOps prod infra pipeline"
on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495348049429:role/ATL-APAC-MUM-DEVOPS-PROD-TERRAFORM-IAAC-IAM-ROLE
          aws-region: ap-south-1

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Run Terraform plan
      - name: Terraform Plan
        working-directory: ./nawc/prod
        run: |
          terraform init -backend-config="backend.hcl"
          terraform plan

      # 4. Run Terraform
      - name: Terraform Apply
        working-directory: ./nawc/prod
        run: |
          terraform apply -auto-approve
