name: "Common Resources NON SAP prod infra pipeline"
on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185863138492:role/crosssetupB
          aws-region: ap-south-1

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Run Terraform plan
      - name: Terraform Plan
        working-directory: ./common
        run: |
          terraform init -backend-config="backend.hcl"
      #     terraform plan

      # 4. Run Terraform
      - name: Terraform Apply
        working-directory: ./common
        run: |
          terraform apply -auto-approve
